//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Responsibilities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorksId { get; set; }
        public int EmployeeId { get; set; }
        public int TypesOfWorkId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TypesOfWork TypesOfWork { get; set; }
    }
}
